### ISSUE TITLE
Qt + Verbosity crashes

### ISSUE THREAD

**Issue by Epsilqn** [Epsilqn/PyOverflow#16]
Upon running qt with verbosity:
```py
Traceback (most recent call last):
  File "setupqt.py", line 85, in submitted
    def submitted(): run_compile()
  File "setupqt.py", line 154, in run_compile
    if verbose: libll.setText(libll + ret)
TypeError: unsupported operand type(s) for +: 'QLabel' and 'NoneType'
Aborted (core dumped)
```
Think this can be fixed with the following edit to `setupqt.py`:
```diff
+ if verbose: libll.setText(libll.text() + ret)
- if verbose: libll.setText(libll + ret)
```

**Comment by Epsilqn** [comment]
That change threw the following:
```py
Traceback (most recent call last):
  File "setupqt.py", line 85, in submitted
    def submitted(): run_compile()
  File "setupqt.py", line 154, in run_compile
    if verbose: libll.setText(libll.text() + ret)
TypeError: can only concatenate str (not "NoneType") to str
Aborted (core dumped)
```
I think that's because of this in `compile.py`:
```py
    if vbs:
        output = f"{ccmd}\n"
        output += subprocess.check_output([ccmd], stderr=subprocess.STDOUT, shell=True, text=True)
        output += f"{pycmd}\n"
        output += subprocess.check_output([pycmd], stderr=subprocess.STDOUT, shell=True, text=True)
        output += f"Installed module {lib}.c"
```
This is supposed to return `output` but it doesn't. I'll try changing this and I'll see what happens.

**Comment by Epsilqn** [comment]
This works now, am going to push commits and release 1.0.1.
