### ISSUE TITLE
Underflow errors in calculation

### ISSUE THREAD

**Issue by Epsilqn** [Epsilqn/PyOverflow#2]
When attempting an underflow, the following traceback is thrown: 

```py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    one.sub(1)
  File "C:\Users\epsil\PycharmProjects\PyOverflow\intx\intx.py", line 16, in sub
    if self.value - smn < self.min: self.value = self.value - addend - self.min
NameError: name 'addend' is not defined
```

This can be solved by changing line 16 in `intx/intx.py`:
```diff
+ if self.value - smn < self.min: self.value = self.value - smn - self.min
- if self.value - smn < self.min: self.value = self.value - addend - self.min
```

**Comment by Epsilqn** [comment]
Issue solved in commit https://github.com/Epsilqn/PyOverflow/commit/e5b5ad4ab719e199e69b099055395f4126a2c3e3 (e5b5ad4) on branch `staging`.
